"""add_password_reset_tokens

Revision ID: 0ea6e92476b2
Revises: l0m1n2o3p4q5
Create Date: 2026-06-16 09:59:14.380860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea6e92476b2'
down_revision: Union[str, Sequence[str], None] = 'l0m1n2o3p4q5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_consent_student_id'), table_name='consent')
    op.create_index(op.f('ix_consent_student_id'), 'consent', ['student_id'], unique=True)
    op.drop_index(op.f('idx_availability_psychologist_date'), table_name='psychologist_availability')
    op.drop_constraint(op.f('uq_safety_plans_student_id'), 'safety_plans', type_='unique')
    op.drop_index(op.f('ix_safety_plans_student_id'), table_name='safety_plans')
    op.create_index(op.f('ix_safety_plans_student_id'), 'safety_plans', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_plans_student_id'), table_name='safety_plans')
    op.create_index(op.f('ix_safety_plans_student_id'), 'safety_plans', ['student_id'], unique=False)
    op.create_unique_constraint(op.f('uq_safety_plans_student_id'), 'safety_plans', ['student_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_availability_psychologist_date'), 'psychologist_availability', ['psychologist_id', 'date', 'start_time', 'end_time'], unique=False)
    op.drop_index(op.f('ix_consent_student_id'), table_name='consent')
    op.create_index(op.f('ix_consent_student_id'), 'consent', ['student_id'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
