"""add_campus_one_tokens

Revision ID: 34304967ffe4
Revises: c4d5e6f7g8h9
Create Date: 2026-06-02 19:58:22.274690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34304967ffe4'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7g8h9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_appointments_psychologist_time')
    op.execute('DROP INDEX IF EXISTS idx_appointments_student_id2')
    op.execute('DROP INDEX IF EXISTS idx_notifications_user_read')
    op.execute('DROP INDEX IF EXISTS idx_availability_psychologist')
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_psychologist_availability_psychologist_id') THEN CREATE INDEX ix_psychologist_availability_psychologist_id ON psychologist_availability (psychologist_id); END IF; END $$")
    op.execute('DROP INDEX IF EXISTS idx_busy_blocks_psychologist_time')
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_psychologist_busy_blocks_psychologist_id') THEN CREATE INDEX ix_psychologist_busy_blocks_psychologist_id ON psychologist_busy_blocks (psychologist_id); END IF; END $$")
    op.execute('DROP INDEX IF EXISTS idx_risk_scores_student_computed')
    op.execute('DROP INDEX IF EXISTS idx_students_faculty')
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_students_faculty') THEN CREATE INDEX ix_students_faculty ON students (faculty); END IF; END $$")
    op.add_column('users', sa.Column('campus_one_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('campus_one_refresh_token', sa.Text(), nullable=True))
    op.execute('DROP INDEX IF EXISTS idx_checkins_student_submitted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_checkins_student_submitted'), 'wellness_checkins', ['student_id', 'submitted_at'], unique=False)
    op.drop_column('users', 'campus_one_refresh_token')
    op.drop_column('users', 'campus_one_access_token')
    op.drop_index(op.f('ix_students_faculty'), table_name='students')
    op.create_index(op.f('idx_students_faculty'), 'students', ['faculty'], unique=False)
    op.create_index(op.f('idx_risk_scores_student_computed'), 'risk_scores', ['student_id', 'computed_at'], unique=False)
    op.drop_index(op.f('ix_psychologist_busy_blocks_psychologist_id'), table_name='psychologist_busy_blocks')
    op.create_index(op.f('idx_busy_blocks_psychologist_time'), 'psychologist_busy_blocks', ['psychologist_id', 'block_start', 'block_end'], unique=False)
    op.drop_index(op.f('ix_psychologist_availability_psychologist_id'), table_name='psychologist_availability')
    op.create_index(op.f('idx_availability_psychologist'), 'psychologist_availability', ['psychologist_id', 'day_of_week'], unique=False)
    op.create_index(op.f('idx_notifications_user_read'), 'notifications', ['user_id', 'read'], unique=False)
    op.create_index(op.f('idx_appointments_student_id2'), 'appointments', ['student_id'], unique=False)
    op.create_index(op.f('idx_appointments_psychologist_time'), 'appointments', ['psychologist_id', 'start_time'], unique=False)
    # ### end Alembic commands ###
