"""add feedback table

Revision ID: 858cc9521e7a
Revises: 1e6c4a7b2d9f
Create Date: 2026-05-23 12:25:43.940806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '858cc9521e7a'
down_revision: Union[str, Sequence[str], None] = '1e6c4a7b2d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop legacy idx_* indexes only if they exist (absent on fresh databases)
    op.execute('DROP INDEX IF EXISTS idx_appointments_psychologist_id')
    op.execute('DROP INDEX IF EXISTS idx_appointments_start_time')
    op.execute('DROP INDEX IF EXISTS idx_appointments_status')
    op.execute('DROP INDEX IF EXISTS idx_appointments_student_id')
    op.execute('DROP INDEX IF EXISTS idx_audit_logs_timestamp')
    op.execute('DROP INDEX IF EXISTS idx_audit_logs_user_id')
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'audit_logs_user_id_fkey') THEN ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_user_id_fkey; END IF; END $$")
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'consent_student_id_key') THEN ALTER TABLE consent DROP CONSTRAINT consent_student_id_key; END IF; END $$")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_consent_student_id') THEN CREATE UNIQUE INDEX ix_consent_student_id ON consent (student_id); END IF; END $$")
    op.execute('DROP INDEX IF EXISTS idx_crisis_logs_severity')
    op.execute('DROP INDEX IF EXISTS idx_crisis_logs_student_id')
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'crisis_logs_appointment_id_fkey') THEN ALTER TABLE crisis_logs DROP CONSTRAINT crisis_logs_appointment_id_fkey; END IF; END $$")
    op.create_foreign_key(None, 'crisis_logs', 'appointments', ['appointment_id'], ['id'])
    op.execute('DROP INDEX IF EXISTS idx_notifications_status')
    op.execute('DROP INDEX IF EXISTS idx_notifications_user_id')
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notifications_user_id_fkey') THEN ALTER TABLE notifications DROP CONSTRAINT notifications_user_id_fkey; END IF; END $$")
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.execute('DROP INDEX IF EXISTS idx_refresh_tokens_user_id')
    op.alter_column('resources', 'type',
               existing_type=postgresql.ENUM('article', 'video', 'exercise', name='resourcetype'),
               type_=sa.Enum('article', 'video', 'exercise', name='resourcetype', native_enum=False),
               existing_nullable=False)
    op.alter_column('risk_overrides', 'override_tier',
               existing_type=postgresql.ENUM('green', 'amber', 'red', 'critical', name='risktier'),
               type_=sa.Enum('green', 'amber', 'red', 'critical', name='risktier', native_enum=False),
               existing_nullable=False)
    op.alter_column('risk_scores', 'tier',
               existing_type=postgresql.ENUM('green', 'amber', 'red', 'critical', name='risktier'),
               type_=sa.Enum('green', 'amber', 'red', 'critical', name='risktier', native_enum=False),
               existing_nullable=False)
    op.execute('DROP INDEX IF EXISTS idx_risk_scores_student_id')
    op.execute('DROP INDEX IF EXISTS idx_risk_scores_tier')
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_risk_scores_student_id') THEN CREATE INDEX ix_risk_scores_student_id ON risk_scores (student_id); END IF; END $$")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_risk_scores_tier') THEN CREATE INDEX ix_risk_scores_tier ON risk_scores (tier); END IF; END $$")
    op.execute('DROP INDEX IF EXISTS idx_staff_staff_id')
    op.execute('DROP INDEX IF EXISTS idx_students_assigned_psychologist')
    op.execute('DROP INDEX IF EXISTS idx_students_user_id')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('staff', 'student', name='userrole'),
               type_=sa.Enum('staff', 'student', name='userrole', native_enum=False),
               existing_nullable=False)
    op.execute('DROP INDEX IF EXISTS idx_users_email')
    op.execute('DROP INDEX IF EXISTS idx_users_is_active')
    op.execute('DROP INDEX IF EXISTS idx_users_role')
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_email_key') THEN ALTER TABLE users DROP CONSTRAINT users_email_key; END IF; END $$")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_users_email') THEN CREATE UNIQUE INDEX ix_users_email ON users (email); END IF; END $$")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_users_role') THEN CREATE INDEX ix_users_role ON users (role); END IF; END $$")
    op.alter_column('wellness_checkins', 'type',
               existing_type=postgresql.ENUM('pulse', 'phq9', 'gad7', 'event_triggered', 'crisis', name='wellnesscheckintype'),
               type_=sa.Enum('pulse', 'phq9', 'gad7', 'event_triggered', 'crisis', name='wellnesscheckintype', native_enum=False),
               existing_nullable=False)
    op.execute('DROP INDEX IF EXISTS idx_wellness_checkins_student_id')
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_wellness_checkins_student_id') THEN CREATE INDEX ix_wellness_checkins_student_id ON wellness_checkins (student_id); END IF; END $$")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_checkins_student_id'), table_name='wellness_checkins')
    op.create_index(op.f('idx_wellness_checkins_student_id'), 'wellness_checkins', ['student_id'], unique=False)
    op.alter_column('wellness_checkins', 'type',
               existing_type=sa.Enum('pulse', 'phq9', 'gad7', 'event_triggered', 'crisis', name='wellnesscheckintype', native_enum=False),
               type_=postgresql.ENUM('pulse', 'phq9', 'gad7', 'event_triggered', 'crisis', name='wellnesscheckintype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('staff', 'student', name='userrole', native_enum=False),
               type_=postgresql.ENUM('staff', 'student', name='userrole'),
               existing_nullable=False)
    op.create_index(op.f('idx_students_user_id'), 'students', ['user_id'], unique=False)
    op.create_index(op.f('idx_students_assigned_psychologist'), 'students', ['assigned_psychologist_id'], unique=False)
    op.create_index(op.f('idx_staff_staff_id'), 'staff', ['staff_id'], unique=False)
    op.drop_index(op.f('ix_risk_scores_tier'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_student_id'), table_name='risk_scores')
    op.create_index(op.f('idx_risk_scores_tier'), 'risk_scores', ['tier'], unique=False)
    op.create_index(op.f('idx_risk_scores_student_id'), 'risk_scores', ['student_id'], unique=False)
    op.alter_column('risk_scores', 'tier',
               existing_type=sa.Enum('green', 'amber', 'red', 'critical', name='risktier', native_enum=False),
               type_=postgresql.ENUM('green', 'amber', 'red', 'critical', name='risktier'),
               existing_nullable=False)
    op.alter_column('risk_overrides', 'override_tier',
               existing_type=sa.Enum('green', 'amber', 'red', 'critical', name='risktier', native_enum=False),
               type_=postgresql.ENUM('green', 'amber', 'red', 'critical', name='risktier'),
               existing_nullable=False)
    op.alter_column('resources', 'type',
               existing_type=sa.Enum('article', 'video', 'exercise', name='resourcetype', native_enum=False),
               type_=postgresql.ENUM('article', 'video', 'exercise', name='resourcetype'),
               existing_nullable=False)
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_status'), 'notifications', ['status'], unique=False)
    op.drop_constraint(None, 'crisis_logs', type_='foreignkey')
    op.create_foreign_key(op.f('crisis_logs_appointment_id_fkey'), 'crisis_logs', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_crisis_logs_student_id'), 'crisis_logs', ['student_id'], unique=False)
    op.create_index(op.f('idx_crisis_logs_severity'), 'crisis_logs', ['severity_level'], unique=False)
    op.drop_index(op.f('ix_consent_student_id'), table_name='consent')
    op.create_unique_constraint(op.f('consent_student_id_key'), 'consent', ['student_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_appointments_student_id'), 'appointments', ['student_id'], unique=False)
    op.create_index(op.f('idx_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('idx_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('idx_appointments_psychologist_id'), 'appointments', ['psychologist_id'], unique=False)
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
