"""expand_session_table

Revision ID: c9f87335b6fb
Revises: 34304967ffe4
Create Date: 2026-06-02 20:21:38.813433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9f87335b6fb'
down_revision: Union[str, Sequence[str], None] = '34304967ffe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('sessions', sa.Column('audio_files', sa.JSON(), nullable=True))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'sessions', 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('sessions', 'audio_files')
    op.drop_column('sessions', 'status')
    op.drop_column('sessions', 'notes')
    op.drop_column('sessions', 'transcript')
    # ### end Alembic commands ###
